const PDFDocument = require('pdfkit');
const XLSX = require('xlsx');
const { formatCurrency } = require('../utils/formatters');
const { labelDateRange } = require('./report-export.service');

const buildWorkbookBuffer = ({ rows, sheetName = 'Export' }) => {
  const workbook = XLSX.utils.book_new();
  const sheet = XLSX.utils.aoa_to_sheet(rows);
  sheet['!cols'] = [
    { wch: 18 },
    { wch: 16 },
    { wch: 16 },
    { wch: 14 },
    { wch: 20 },
    { wch: 32 },
  ];
  XLSX.utils.book_append_sheet(workbook, sheet, sheetName);
  return XLSX.write(workbook, { type: 'buffer', bookType: 'xlsx' });
};

const buildExpensesExcel = ({ expenses, filters }) => {
  const totalAmount = expenses.reduce((sum, expense) => sum + Number(expense.amount), 0);
  const rows = [
    ['ExpensePilot Expenses Export'],
    ['Date Range', labelDateRange(filters)],
    ['Category', filters.categoryLabel || 'All categories'],
    ['Search', filters.search || 'N/A'],
    ['Sort', `${filters.sortBy} ${filters.sortOrder}`],
    ['Entries', expenses.length],
    ['Total Amount', totalAmount],
    [],
    ['Date', 'Title', 'Category', 'Amount', 'User Notes', 'Record ID'],
    ...expenses.map((expense) => [
      expense.expenseDate,
      expense.title,
      expense.Category?.name || 'Uncategorized',
      Number(expense.amount),
      expense.notes || '',
      expense.id,
    ]),
  ];

  return buildWorkbookBuffer({
    rows,
    sheetName: 'Expenses',
  });
};

const buildExpensesPdf = ({ expenses, filters }) =>
  new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 36 });
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const totalAmount = expenses.reduce((sum, expense) => sum + Number(expense.amount), 0);

    doc.roundedRect(36, 36, 523, 92, 20).fill('#123458');
    doc.fillColor('#FFFFFF').fontSize(22).text('Expenses Export', 56, 58);
    doc.fillColor('#DCE8F5').fontSize(10).text(`Date range: ${labelDateRange(filters)}`, 56, 92);
    doc.fillColor('#DCE8F5').fontSize(10).text(`Category: ${filters.categoryLabel || 'All categories'}`, 280, 92);

    doc.roundedRect(36, 146, 165, 60, 14).fill('#F8FAFC');
    doc.roundedRect(215, 146, 165, 60, 14).fill('#F8FAFC');
    doc.roundedRect(394, 146, 165, 60, 14).fill('#F8FAFC');
    doc.fillColor('#6B7280').fontSize(10).text('Entries', 50, 164);
    doc.fillColor('#123458').fontSize(16).text(String(expenses.length), 50, 180);
    doc.fillColor('#6B7280').fontSize(10).text('Total Amount', 229, 164);
    doc.fillColor('#123458').fontSize(16).text(formatCurrency(totalAmount), 229, 180);
    doc.fillColor('#6B7280').fontSize(10).text('Search', 408, 164);
    doc.fillColor('#123458').fontSize(12).text(filters.search || 'N/A', 408, 180, { width: 132 });

    let y = 232;
    doc.fillColor('#123458').fontSize(15).text('Expense table', 36, y);
    y += 24;

    const headers = [
      { label: 'Date', x: 36, width: 72 },
      { label: 'Title', x: 112, width: 120 },
      { label: 'Category', x: 236, width: 90 },
      { label: 'Amount', x: 330, width: 75 },
      { label: 'Notes', x: 409, width: 145 },
    ];

    const drawTableHeader = () => {
      doc.rect(36, y, 518, 22).fill('#EAF0F6');
      doc.fillColor('#123458').fontSize(9);
      headers.forEach((header) => {
        doc.text(header.label, header.x + 4, y + 7, { width: header.width - 8 });
      });
      y += 28;
    };

    drawTableHeader();

    expenses.forEach((expense, index) => {
      const rowHeight = 34;
      if (y + rowHeight > 780) {
        doc.addPage();
        y = 48;
        drawTableHeader();
      }

      doc.rect(36, y - 2, 518, rowHeight).fill(index % 2 === 0 ? '#FFFFFF' : '#F9FBFD');
      doc.fillColor('#2F4156').fontSize(8.5);
      doc.text(expense.expenseDate, 40, y + 8, { width: 64 });
      doc.text(expense.title, 116, y + 8, { width: 112 });
      doc.text(expense.Category?.name || 'Uncategorized', 240, y + 8, { width: 82 });
      doc.text(formatCurrency(expense.amount), 334, y + 8, { width: 67 });
      doc.text(expense.notes || '-', 413, y + 8, { width: 137 });
      y += rowHeight;
    });

    doc.fillColor('#6B7280').fontSize(9).text('Generated by ExpensePilot backend export service.', 36, 800);
    doc.end();
  });

module.exports = {
  buildExpensesExcel,
  buildExpensesPdf,
};
